@startuml

hide footbox 

'box "Client" #F7FFFA
Participant "AllergyIntolerance Reporter" as R
'Participant "AllergyIntolerance Consumer" as C
'end box
Participant "AllergyIntolerance Registry" as V

R -> V: [[#be-al-create-1 ~[Create Allergy/Intolerance~]]]
V -> R:  [[#be-al-create-2 ~[Response~]]]


@enduml